[package]
name = "mdbook-keeper"
version = "0.5.0"
edition = "2021"
authors = ["Tom Kunc <tom@tfpk.dev>"]
license = "MIT OR Apache-2.0"
description = "An improved testing experience for mdbook."
documentation = "https://github.com/tfpk/mdbook-keeper/"
repository = "https://github.com/tfpk/mdbook-keeper/"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mdbook_keeper_lib"
path = "src/lib.rs"

[[bin]]
name = "mdbook-keeper"
path = "src/bin.rs"

[dependencies]
anyhow = "1.0.58"
clap = "3.2.8"
mdbook = "0.4.*"
toml = "0.5.11" # Keep pinned until mdbook stops exposing this version in their API.
semver = "1.0.12"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
pulldown-cmark = { version = "0.9", default-features = false }
bytecount = "0.6"
slug = "0.1.4"
cargo_metadata = "0.15.0"
error-chain = "0.12.4"
walkdir = "2.3.2"
current_platform = "0.2.0"
tempfile = "3.3.0"
atty = "0.2.14"
colored = "2.0.0"
sha2 = "0.10.6"
base64-url = "1.4.13"
glob = "0.3.0"
fs_extra = "1.3.0"

# Needed to satisfy error-chain
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(has_error_description_deprecated)'] }
